### ISSUE TITLE
Having a #include in the file leads to the disabling of Souffle highlighting.

### ISSUE THREAD

**Issue by pnappa** [souffle-lang/souffle.vim#4]
I currently have the problem if I open a .dl file that has a `#include file.h`, the syntax highlighting is not as one would expect:

For this file:
```
// an equivalent program that has a rule for each length path, rather than relying on recursion.
.type string

#include "gluemacro.h"

// we are trying to find the paths between these words
.decl goal(worda : string, wordb : string)
goal("be", "bitten").

// edge of the transition graph
.decl edge(worda : string, wordb : string, score : number)

// basic edge
.decl two_path(worda : string, wordb : string, score : number)
two_path(start, end, score) :- edge(start, end, score).
// intermediary (note: i constrained these with goal, as we only use them with the first word as "start")
.decl three_path(worda : string, wordb : string, wordc : string, score : number)
three_path(start, a, end, scoreA + scoreB) :- goal(start, _), two_path(a, end, scoreB), two_path(start, a, scoreA).
// two intermediaries
.decl four_path(worda : string, wordb : string, wordc : string, wordd : string, score : number)
four_path(start, a, b, end, scoreA + scoreB) :- goal(start, _), two_path(b, end, scoreB), three_path(start, a, b, scoreA).
// three intermediaries
.decl five_path(worda : string, wordb : string, wordc : string, wordd : string, worde : string, score : number)
five_path(start, a, b, c, end, scoreA + scoreB) :- goal(start, _), two_path(c, end, scoreB), four_path(start, a, b, c, scoreA).
// four intermediaries (constrained the last one with end too, same reason)
.decl six_path(worda : string, wordb : string, wordc : string, wordd : string, worde : string, wordf : string, score : number)
six_path(start, a, b, c, d, end, scoreA + scoreB) :- goal(start, end), two_path(d, end, scoreB), five_path(start, a, b, c, d, scoreA).

.decl explicit_solution_cat(score : number, path : string)
explicit_solution_cat(score, GLUE6(start, a, b, c, d, end)) :-
    goal(start, end), 
    six_path(start, a, b, c, d, end, score).

.input edge
.output explicit_solution_cat
```

I get this:
![screenshot from 2018-12-01 13-21-53](https://user-images.githubusercontent.com/1394161/49323213-405e6000-f56c-11e8-94a8-b5f4f6af1889.png)

However, if I remove the `#include`, and reload syntax (via typing `:e`), the syntax is as expected:
![screenshot from 2018-12-01 13-22-39](https://user-images.githubusercontent.com/1394161/49323215-46544100-f56c-11e8-8700-121fae8a9059.png)

But if I add it back in (without reloading file), it also appears as expected:

![screenshot from 2018-12-01 13-23-55](https://user-images.githubusercontent.com/1394161/49323223-5ff58880-f56c-11e8-9f61-43eb72f92e29.png)

Yet, if I reload (`:e`), it reverts to the syntax highlighting as per the first image.

**Comment by pnappa** [comment]
btw, using your version from your branch @mmcgr , doesn't fix anything

**Comment by mmcgr** [comment]
The highlighting works for me, so I suspect another setting is conflicting.

**Comment by azreika** [comment]
Highlighting also works fine for me. Has this been sorted?

**Comment by pnappa** [comment]
Aha! found out the reason, it was exclusive to my vim version, so upgrading to a manually built one just worked.
